# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'untitled.ui'
#
# Created by: PyQt5 UI code generator 5.10
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1024, 845)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayoutWidget = QtWidgets.QWidget(self.centralwidget)
        self.verticalLayoutWidget.setGeometry(QtCore.QRect(9, 529, 1021, 271))
        self.verticalLayoutWidget.setObjectName("verticalLayoutWidget")
        self.verticalLayoutMap = QtWidgets.QVBoxLayout(self.verticalLayoutWidget)
        self.verticalLayoutMap.setContentsMargins(0, 0, 0, 0)
        self.verticalLayoutMap.setObjectName("verticalLayoutMap")
        self.horizontalLayoutWidget_3 = QtWidgets.QWidget(self.centralwidget)
        self.horizontalLayoutWidget_3.setGeometry(QtCore.QRect(10, 10, 1021, 291))
        self.horizontalLayoutWidget_3.setObjectName("horizontalLayoutWidget_3")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget_3)
        self.horizontalLayout_3.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.tabWidgetInputCrs = QtWidgets.QTabWidget(self.horizontalLayoutWidget_3)
        self.tabWidgetInputCrs.setObjectName("tabWidgetInputCrs")
        self.tabCompoundInCrs = QtWidgets.QWidget()
        self.tabCompoundInCrs.setObjectName("tabCompoundInCrs")
        self.tabWidgetInputCrs.addTab(self.tabCompoundInCrs, "")
        self.tabCrsInHV = QtWidgets.QWidget()
        self.tabCrsInHV.setObjectName("tabCrsInHV")
        self.verticalLayoutWidget_4 = QtWidgets.QWidget(self.tabCrsInHV)
        self.verticalLayoutWidget_4.setGeometry(QtCore.QRect(0, 0, 501, 256))
        self.verticalLayoutWidget_4.setObjectName("verticalLayoutWidget_4")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.verticalLayoutWidget_4)
        self.verticalLayout_3.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout()
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.label_4 = QtWidgets.QLabel(self.verticalLayoutWidget_4)
        self.label_4.setObjectName("label_4")
        self.horizontalLayout_5.addWidget(self.label_4)
        self.label_9 = QtWidgets.QLabel(self.verticalLayoutWidget_4)
        self.label_9.setMaximumSize(QtCore.QSize(150, 16777215))
        self.label_9.setObjectName("label_9")
        self.horizontalLayout_5.addWidget(self.label_9)
        self.verticalLayout_2.addLayout(self.horizontalLayout_5)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.comboBoxCrsInH = QtWidgets.QComboBox(self.verticalLayoutWidget_4)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(1)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.comboBoxCrsInH.sizePolicy().hasHeightForWidth())
        self.comboBoxCrsInH.setSizePolicy(sizePolicy)
        self.comboBoxCrsInH.setEditable(True)
        self.comboBoxCrsInH.setObjectName("comboBoxCrsInH")
        self.horizontalLayout_2.addWidget(self.comboBoxCrsInH)
        self.comboBoxUnitsInH = QtWidgets.QComboBox(self.verticalLayoutWidget_4)
        self.comboBoxUnitsInH.setMinimumSize(QtCore.QSize(150, 0))
        self.comboBoxUnitsInH.setEditable(True)
        self.comboBoxUnitsInH.setObjectName("comboBoxUnitsInH")
        self.horizontalLayout_2.addWidget(self.comboBoxUnitsInH)
        self.verticalLayout_2.addLayout(self.horizontalLayout_2)
        self.verticalLayout_3.addLayout(self.verticalLayout_2)
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.label = QtWidgets.QLabel(self.verticalLayoutWidget_4)
        self.label.setObjectName("label")
        self.horizontalLayout_4.addWidget(self.label)
        self.label_3 = QtWidgets.QLabel(self.verticalLayoutWidget_4)
        self.label_3.setMaximumSize(QtCore.QSize(150, 16777215))
        self.label_3.setObjectName("label_3")
        self.horizontalLayout_4.addWidget(self.label_3)
        self.verticalLayout.addLayout(self.horizontalLayout_4)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.comboBoxCrsInV = QtWidgets.QComboBox(self.verticalLayoutWidget_4)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(1)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.comboBoxCrsInV.sizePolicy().hasHeightForWidth())
        self.comboBoxCrsInV.setSizePolicy(sizePolicy)
        self.comboBoxCrsInV.setEditable(True)
        self.comboBoxCrsInV.setObjectName("comboBoxCrsInV")
        self.horizontalLayout.addWidget(self.comboBoxCrsInV)
        self.comboBoxUnitsInV = QtWidgets.QComboBox(self.verticalLayoutWidget_4)
        self.comboBoxUnitsInV.setMinimumSize(QtCore.QSize(150, 0))
        self.comboBoxUnitsInV.setEditable(True)
        self.comboBoxUnitsInV.setObjectName("comboBoxUnitsInV")
        self.horizontalLayout.addWidget(self.comboBoxUnitsInV)
        self.verticalLayout.addLayout(self.horizontalLayout)
        self.verticalLayout_3.addLayout(self.verticalLayout)
        self.verticalLayout_10 = QtWidgets.QVBoxLayout()
        self.verticalLayout_10.setObjectName("verticalLayout_10")
        self.label_7 = QtWidgets.QLabel(self.verticalLayoutWidget_4)
        self.label_7.setObjectName("label_7")
        self.verticalLayout_10.addWidget(self.label_7)
        self.horizontalLayout_8 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_8.setObjectName("horizontalLayout_8")
        self.comboBoxGeoidInV = QtWidgets.QComboBox(self.verticalLayoutWidget_4)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(1)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.comboBoxGeoidInV.sizePolicy().hasHeightForWidth())
        self.comboBoxGeoidInV.setSizePolicy(sizePolicy)
        self.comboBoxGeoidInV.setEditable(True)
        self.comboBoxGeoidInV.setObjectName("comboBoxGeoidInV")
        self.horizontalLayout_8.addWidget(self.comboBoxGeoidInV)
        self.verticalLayout_10.addLayout(self.horizontalLayout_8)
        self.verticalLayout_3.addLayout(self.verticalLayout_10)
        self.verticalLayout_11 = QtWidgets.QVBoxLayout()
        self.verticalLayout_11.setObjectName("verticalLayout_11")
        self.label_8 = QtWidgets.QLabel(self.verticalLayoutWidget_4)
        self.label_8.setObjectName("label_8")
        self.verticalLayout_11.addWidget(self.label_8)
        self.horizontalLayout_9 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_9.setObjectName("horizontalLayout_9")
        self.doubleSpinBoxEpochIn = QtWidgets.QDoubleSpinBox(self.verticalLayoutWidget_4)
        self.doubleSpinBoxEpochIn.setObjectName("doubleSpinBoxEpochIn")
        self.horizontalLayout_9.addWidget(self.doubleSpinBoxEpochIn)
        self.pushButtonPickEpochIn = QtWidgets.QPushButton(self.verticalLayoutWidget_4)
        self.pushButtonPickEpochIn.setObjectName("pushButtonPickEpochIn")
        self.horizontalLayout_9.addWidget(self.pushButtonPickEpochIn)
        self.verticalLayout_11.addLayout(self.horizontalLayout_9)
        self.verticalLayout_3.addLayout(self.verticalLayout_11)
        self.tabWidgetInputCrs.addTab(self.tabCrsInHV, "")
        self.tabCrsInText = QtWidgets.QWidget()
        self.tabCrsInText.setObjectName("tabCrsInText")
        self.tabWidgetInputCrs.addTab(self.tabCrsInText, "")
        self.horizontalLayout_3.addWidget(self.tabWidgetInputCrs)
        self.tabWidgetOutputCrs = QtWidgets.QTabWidget(self.horizontalLayoutWidget_3)
        self.tabWidgetOutputCrs.setObjectName("tabWidgetOutputCrs")
        self.tabCompoundOutCrs = QtWidgets.QWidget()
        self.tabCompoundOutCrs.setObjectName("tabCompoundOutCrs")
        self.tabWidgetOutputCrs.addTab(self.tabCompoundOutCrs, "")
        self.tabCrsOutHV = QtWidgets.QWidget()
        self.tabCrsOutHV.setObjectName("tabCrsOutHV")
        self.verticalLayoutWidget_5 = QtWidgets.QWidget(self.tabCrsOutHV)
        self.verticalLayoutWidget_5.setGeometry(QtCore.QRect(0, 0, 501, 256))
        self.verticalLayoutWidget_5.setObjectName("verticalLayoutWidget_5")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout(self.verticalLayoutWidget_5)
        self.verticalLayout_4.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.verticalLayout_5 = QtWidgets.QVBoxLayout()
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.horizontalLayout_6 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_6.setObjectName("horizontalLayout_6")
        self.label_5 = QtWidgets.QLabel(self.verticalLayoutWidget_5)
        self.label_5.setObjectName("label_5")
        self.horizontalLayout_6.addWidget(self.label_5)
        self.label_10 = QtWidgets.QLabel(self.verticalLayoutWidget_5)
        self.label_10.setMaximumSize(QtCore.QSize(150, 16777215))
        self.label_10.setObjectName("label_10")
        self.horizontalLayout_6.addWidget(self.label_10)
        self.verticalLayout_5.addLayout(self.horizontalLayout_6)
        self.horizontalLayout_7 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_7.setObjectName("horizontalLayout_7")
        self.comboBoxCrsOutH = QtWidgets.QComboBox(self.verticalLayoutWidget_5)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(1)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.comboBoxCrsOutH.sizePolicy().hasHeightForWidth())
        self.comboBoxCrsOutH.setSizePolicy(sizePolicy)
        self.comboBoxCrsOutH.setEditable(True)
        self.comboBoxCrsOutH.setObjectName("comboBoxCrsOutH")
        self.horizontalLayout_7.addWidget(self.comboBoxCrsOutH)
        self.comboBoxUnitsOutH = QtWidgets.QComboBox(self.verticalLayoutWidget_5)
        self.comboBoxUnitsOutH.setMinimumSize(QtCore.QSize(150, 0))
        self.comboBoxUnitsOutH.setEditable(True)
        self.comboBoxUnitsOutH.setObjectName("comboBoxUnitsOutH")
        self.horizontalLayout_7.addWidget(self.comboBoxUnitsOutH)
        self.verticalLayout_5.addLayout(self.horizontalLayout_7)
        self.verticalLayout_4.addLayout(self.verticalLayout_5)
        self.verticalLayout_6 = QtWidgets.QVBoxLayout()
        self.verticalLayout_6.setObjectName("verticalLayout_6")
        self.horizontalLayout_11 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_11.setObjectName("horizontalLayout_11")
        self.label_2 = QtWidgets.QLabel(self.verticalLayoutWidget_5)
        self.label_2.setObjectName("label_2")
        self.horizontalLayout_11.addWidget(self.label_2)
        self.label_6 = QtWidgets.QLabel(self.verticalLayoutWidget_5)
        self.label_6.setMaximumSize(QtCore.QSize(150, 16777215))
        self.label_6.setObjectName("label_6")
        self.horizontalLayout_11.addWidget(self.label_6)
        self.verticalLayout_6.addLayout(self.horizontalLayout_11)
        self.horizontalLayout_12 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_12.setObjectName("horizontalLayout_12")
        self.comboBoxCrsOutV = QtWidgets.QComboBox(self.verticalLayoutWidget_5)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(1)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.comboBoxCrsOutV.sizePolicy().hasHeightForWidth())
        self.comboBoxCrsOutV.setSizePolicy(sizePolicy)
        self.comboBoxCrsOutV.setEditable(True)
        self.comboBoxCrsOutV.setObjectName("comboBoxCrsOutV")
        self.horizontalLayout_12.addWidget(self.comboBoxCrsOutV)
        self.comboBoxUnitsOutV = QtWidgets.QComboBox(self.verticalLayoutWidget_5)
        self.comboBoxUnitsOutV.setMinimumSize(QtCore.QSize(150, 0))
        self.comboBoxUnitsOutV.setEditable(True)
        self.comboBoxUnitsOutV.setObjectName("comboBoxUnitsOutV")
        self.horizontalLayout_12.addWidget(self.comboBoxUnitsOutV)
        self.verticalLayout_6.addLayout(self.horizontalLayout_12)
        self.verticalLayout_4.addLayout(self.verticalLayout_6)
        self.verticalLayout_12 = QtWidgets.QVBoxLayout()
        self.verticalLayout_12.setObjectName("verticalLayout_12")
        self.label_11 = QtWidgets.QLabel(self.verticalLayoutWidget_5)
        self.label_11.setObjectName("label_11")
        self.verticalLayout_12.addWidget(self.label_11)
        self.horizontalLayout_13 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_13.setObjectName("horizontalLayout_13")
        self.comboBoxGeoidOutV = QtWidgets.QComboBox(self.verticalLayoutWidget_5)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(1)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.comboBoxGeoidOutV.sizePolicy().hasHeightForWidth())
        self.comboBoxGeoidOutV.setSizePolicy(sizePolicy)
        self.comboBoxGeoidOutV.setEditable(True)
        self.comboBoxGeoidOutV.setObjectName("comboBoxGeoidOutV")
        self.horizontalLayout_13.addWidget(self.comboBoxGeoidOutV)
        self.verticalLayout_12.addLayout(self.horizontalLayout_13)
        self.verticalLayout_4.addLayout(self.verticalLayout_12)
        self.verticalLayout_13 = QtWidgets.QVBoxLayout()
        self.verticalLayout_13.setObjectName("verticalLayout_13")
        self.label_12 = QtWidgets.QLabel(self.verticalLayoutWidget_5)
        self.label_12.setObjectName("label_12")
        self.verticalLayout_13.addWidget(self.label_12)
        self.horizontalLayout_14 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_14.setObjectName("horizontalLayout_14")
        self.doubleSpinBoxEpochOut = QtWidgets.QDoubleSpinBox(self.verticalLayoutWidget_5)
        self.doubleSpinBoxEpochOut.setObjectName("doubleSpinBoxEpochOut")
        self.horizontalLayout_14.addWidget(self.doubleSpinBoxEpochOut)
        self.pushButtonPickEpochOut = QtWidgets.QPushButton(self.verticalLayoutWidget_5)
        self.pushButtonPickEpochOut.setObjectName("pushButtonPickEpochOut")
        self.horizontalLayout_14.addWidget(self.pushButtonPickEpochOut)
        self.verticalLayout_13.addLayout(self.horizontalLayout_14)
        self.verticalLayout_4.addLayout(self.verticalLayout_13)
        self.tabWidgetOutputCrs.addTab(self.tabCrsOutHV, "")
        self.tabCrsOutText = QtWidgets.QWidget()
        self.tabCrsOutText.setObjectName("tabCrsOutText")
        self.tabWidgetOutputCrs.addTab(self.tabCrsOutText, "")
        self.horizontalLayout_3.addWidget(self.tabWidgetOutputCrs)
        self.horizontalLayoutWidget_4 = QtWidgets.QWidget(self.centralwidget)
        self.horizontalLayoutWidget_4.setGeometry(QtCore.QRect(10, 310, 1011, 131))
        self.horizontalLayoutWidget_4.setObjectName("horizontalLayoutWidget_4")
        self.horizontalLayout_10 = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget_4)
        self.horizontalLayout_10.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_10.setObjectName("horizontalLayout_10")
        self.tableWidgetInputCrs = QtWidgets.QTableWidget(self.horizontalLayoutWidget_4)
        self.tableWidgetInputCrs.setRowCount(1)
        self.tableWidgetInputCrs.setObjectName("tableWidgetInputCrs")
        self.tableWidgetInputCrs.setColumnCount(3)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidgetInputCrs.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidgetInputCrs.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidgetInputCrs.setHorizontalHeaderItem(2, item)
        self.tableWidgetInputCrs.horizontalHeader().setCascadingSectionResizes(False)
        self.tableWidgetInputCrs.verticalHeader().setCascadingSectionResizes(False)
        self.horizontalLayout_10.addWidget(self.tableWidgetInputCrs)
        self.pushButton = QtWidgets.QPushButton(self.horizontalLayoutWidget_4)
        self.pushButton.setObjectName("pushButton")
        self.horizontalLayout_10.addWidget(self.pushButton)
        self.tableWidgetOutputCrs = QtWidgets.QTableWidget(self.horizontalLayoutWidget_4)
        self.tableWidgetOutputCrs.setObjectName("tableWidgetOutputCrs")
        self.tableWidgetOutputCrs.setColumnCount(0)
        self.tableWidgetOutputCrs.setRowCount(0)
        self.horizontalLayout_10.addWidget(self.tableWidgetOutputCrs)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1024, 22))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        self.tabWidgetInputCrs.setCurrentIndex(1)
        self.tabWidgetOutputCrs.setCurrentIndex(1)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.tabWidgetInputCrs.setTabText(self.tabWidgetInputCrs.indexOf(self.tabCompoundInCrs), _translate("MainWindow", "Compound / Geographic 3D"))
        self.label_4.setText(_translate("MainWindow", "Horizontal CRS"))
        self.label_9.setText(_translate("MainWindow", "Units"))
        self.label.setText(_translate("MainWindow", "Vertical CRS"))
        self.label_3.setText(_translate("MainWindow", "Units"))
        self.label_7.setText(_translate("MainWindow", "Vertical Geoid File"))
        self.label_8.setText(_translate("MainWindow", "Epoch"))
        self.pushButtonPickEpochIn.setText(_translate("MainWindow", "Pick date..."))
        self.tabWidgetInputCrs.setTabText(self.tabWidgetInputCrs.indexOf(self.tabCrsInHV), _translate("MainWindow", "Horizontal & Vertical CRS"))
        self.tabWidgetInputCrs.setTabText(self.tabWidgetInputCrs.indexOf(self.tabCrsInText), _translate("MainWindow", "WKT"))
        self.tabWidgetOutputCrs.setTabText(self.tabWidgetOutputCrs.indexOf(self.tabCompoundOutCrs), _translate("MainWindow", "Compound / Geographic 3D"))
        self.label_5.setText(_translate("MainWindow", "Horizontal CRS"))
        self.label_10.setText(_translate("MainWindow", "Units"))
        self.label_2.setText(_translate("MainWindow", "Vertical CRS"))
        self.label_6.setText(_translate("MainWindow", "Units"))
        self.label_11.setText(_translate("MainWindow", "Vertical Geoid File"))
        self.label_12.setText(_translate("MainWindow", "Epoch"))
        self.pushButtonPickEpochOut.setText(_translate("MainWindow", "Pick date..."))
        self.tabWidgetOutputCrs.setTabText(self.tabWidgetOutputCrs.indexOf(self.tabCrsOutHV), _translate("MainWindow", "Horizontal & Vertical CRS"))
        self.tabWidgetOutputCrs.setTabText(self.tabWidgetOutputCrs.indexOf(self.tabCrsOutText), _translate("MainWindow", "WKT"))
        item = self.tableWidgetInputCrs.horizontalHeaderItem(0)
        item.setText(_translate("MainWindow", "Longitude"))
        item = self.tableWidgetInputCrs.horizontalHeaderItem(1)
        item.setText(_translate("MainWindow", "Latitude"))
        item = self.tableWidgetInputCrs.horizontalHeaderItem(2)
        item.setText(_translate("MainWindow", "Altitude"))
        self.pushButton.setText(_translate("MainWindow", "PushButton"))

